server:
  port: 8888 #修改端口号 注意冒号后面需要有空格
  servlet:
    context-path: /sell

##日志配置
#logging:
#  pattern:
#    console: "%d-%msg%n"  #  控制台输出配置,%d：日期，%msg：信息 %n:换行
#  file: D://weixin_sell//log//logback.log #日志输出文件位置
#  level:
#    root: debug #日志级别
spring:
  druid:
    url: jdbc:mysql://192.168.1.164:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    maxActive: 30 #最大链接数
    maxWait: 10000 #获得链接的最大等待时间
  jpa:
    show-sql: true  #显示sql语句

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null #返回json时，忽悠null
  wechat:
    appid: wxcec0b9e65c084712
    secret: 05a7e861c1985ced86af77fb8f7163bc
    mchId: 1529533061
    mchKey: qwertyuiopasdfghjklzxcvbnm123456 #密匙(在微信支付平台自行设置,要求32位.建议使用随机密码)
    keyPath: F:\下载文件\05微信点餐项目\day07\微信服务号信息_资料\证书\1529533061_20190327_cert\apiclient_cert.p12
    notifyUrl: http://xmccjyqs.natapp1.cc/sell/pay/notify